# Generated by Django 2.1.2 on 2018-10-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetcastModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(default=3, max_length=1, verbose_name='Количество дней')),
                ('temperature', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TempModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата/Время')),
                ('temperature', models.IntegerField(verbose_name='Температура')),
            ],
        ),
    ]
