# Generated by Django 2.1.2 on 2018-10-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metcastmodel',
            name='days',
            field=models.CharField(choices=[(3, 3), (5, 5), (7, 7)], default=3, max_length=1, verbose_name='Количество дней'),
        ),
        migrations.AlterField(
            model_name='metcastmodel',
            name='temperature',
            field=models.IntegerField(verbose_name='Температура'),
        ),
    ]
